In [1]:
import numpy
import pandas
import matplotlib

In [3]:
inputs = [1, 2, 3]
weights = [0.2, 0.8, -0.5]
bias = 2

output = inputs[0] * weights[0] + inputs[1] * weights[1] + inputs[2] * weights[2] + bias
print(output)

2.3


In [4]:
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

for i in range(len(inputs)):
    output += inputs[i] * weights[i]
output += bias
print(output)

7.1


## With Multiple Weights(Neurons) & Biases

In [11]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_out = [] # Output for current layer 

for neuron_weights, neuron_bias in zip(weights,biases):
    neuron_out = 0 # Output of given neuron
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_out += n_input * weight
    neuron_out += neuron_bias
    layer_out.append(neuron_out)

print(layer_out)

[4.8, 1.21, 2.385]


## With Numpy Dot Product

In [13]:
import numpy as np
inputs = [1, 2, 3, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

output = np.dot(inputs, weights) + bias
print(output)

4.8


In [17]:


# Inputs means data points being gathered from different sensors
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_out = np.dot(weights, inputs) + biases
print(layer_out)

[4.8   1.21  2.385]


## With multiple data points from each sensor

In [28]:
# Batch of data means all data are being sliced into different sets (4 parts of 16000, each set consists of 4000 data points)
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0], [0.5, -0.91, 0.26, -0.5], [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]
biases2 = [-1, 2, -0.5]

layer1_output = np.dot(inputs, np.array(weights).T) + biases
layer2_output = np.dot(layer1_output, np.array(weights2).T) + biases2
print(layer2_output)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [ ]:
X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]